# Generated by Django 5.2.6 on 2026-09-09 16:38

import apps.schemes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fix",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("title", models.JSONField()),
                ("steps", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="IncomeBucket",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("order", models.PositiveIntegerField()),
                ("min", models.FloatField(blank=True, null=True)),
                ("upper", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single_select", "single_select"),
                            ("number", "number"),
                            ("pincode", "pincode"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.JSONField()),
                ("options", models.JSONField(blank=True, null=True)),
                ("cols", models.PositiveIntegerField(blank=True, null=True)),
                ("optional", models.BooleanField(default=False)),
                ("show_if", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("message", models.JSONField()),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("order", models.PositiveIntegerField(unique=True)),
                ("name", models.JSONField()),
                (
                    "summ",
                    models.JSONField(default=apps.schemes.models._empty_localized),
                ),
                (
                    "department",
                    models.JSONField(default=apps.schemes.models._empty_localized),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash_transfer", "cash_transfer"),
                            ("subsidy", "subsidy"),
                            ("in_kind", "in_kind"),
                            ("service", "service"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("karnataka", "karnataka"),
                            ("karnataka_central", "karnataka_central"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "benefit",
                    models.JSONField(default=apps.schemes.models._empty_localized),
                ),
                (
                    "amount",
                    models.JSONField(default=apps.schemes.models._empty_localized),
                ),
                (
                    "deadline",
                    models.JSONField(default=apps.schemes.models._empty_localized),
                ),
                ("eligibility_criteria", models.JSONField(default=list)),
                ("application_steps", models.JSONField(default=list)),
                ("docs", models.JSONField(default=list)),
                ("channels", models.JSONField(default=list)),
                ("route", models.JSONField(blank=True, null=True)),
                ("criteria_note", models.JSONField(blank=True, null=True)),
                ("rules", models.JSONField(default=apps.schemes.models._empty_rules)),
                (
                    "confidence_note",
                    models.CharField(default="screening_only", max_length=64),
                ),
                ("last_verified", models.DateField()),
                (
                    "source_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "source_note",
                    models.JSONField(default=apps.schemes.models._empty_localized),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
