# Generated by Django 5.2.6 on 2026-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scheme_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='stage',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheme',
            name='amount_inr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='amount_period',
            field=models.CharField(blank=True, choices=[('month', 'month'), ('one-time', 'one-time'), ('year', 'year')], default='', max_length=16),
        ),
    ]
